PRAGMA foreign_keys=OFF;
-- Seed Data for NomaWork

-- 타임존 데이터
INSERT OR IGNORE INTO timezones (name, offset_hours, utc_label, region, major_cities) VALUES
  ('Pacific Time', -8, 'UTC-8', 'Americas', 'Los Angeles, Vancouver, Seattle'),
  ('Mountain Time', -7, 'UTC-7', 'Americas', 'Denver, Phoenix, Calgary'),
  ('Central Time', -6, 'UTC-6', 'Americas', 'Chicago, Dallas, Mexico City'),
  ('Eastern Time', -5, 'UTC-5', 'Americas', 'New York, Toronto, Miami'),
  ('Brazil Time', -3, 'UTC-3', 'Americas', 'São Paulo, Rio de Janeiro, Buenos Aires'),
  ('UTC', 0, 'UTC+0', 'Europe', 'London, Dublin, Lisbon'),
  ('Central European Time', 1, 'UTC+1', 'Europe', 'Paris, Berlin, Madrid, Rome'),
  ('Eastern European Time', 2, 'UTC+2', 'Europe', 'Athens, Helsinki, Bucharest'),
  ('Moscow Time', 3, 'UTC+3', 'Europe', 'Moscow, Istanbul, Riyadh'),
  ('UAE Time', 4, 'UTC+4', 'Asia', 'Dubai, Abu Dhabi'),
  ('Pakistan Time', 5, 'UTC+5', 'Asia', 'Karachi, Lahore, Islamabad'),
  ('India Time', 5.5, 'UTC+5:30', 'Asia', 'Mumbai, Delhi, Bangalore, Chennai'),
  ('Bangladesh Time', 6, 'UTC+6', 'Asia', 'Dhaka, Chittagong'),
  ('Indochina Time', 7, 'UTC+7', 'Asia', 'Bangkok, Ho Chi Minh, Hanoi, Jakarta'),
  ('China Standard Time', 8, 'UTC+8', 'Asia', 'Beijing, Shanghai, Singapore, Taipei, Kuala Lumpur'),
  ('Korea Standard Time', 9, 'UTC+9', 'Asia', 'Seoul, Tokyo, Osaka, Fukuoka'),
  ('Australian Eastern Time', 10, 'UTC+10', 'Oceania', 'Sydney, Melbourne, Brisbane'),
  ('New Zealand Time', 12, 'UTC+12', 'Oceania', 'Auckland, Wellington');

-- 생활비 지수
INSERT OR IGNORE INTO cost_of_living (country, city, index_value, rent_index, monthly_budget_usd) VALUES
  ('United States', 'New York', 100, 100, 4500),
  ('United States', 'San Francisco', 105, 115, 4800),
  ('United States', 'Austin', 75, 72, 3200),
  ('United Kingdom', 'London', 88, 85, 3800),
  ('Germany', 'Berlin', 68, 55, 2800),
  ('Netherlands', 'Amsterdam', 78, 80, 3200),
  ('Portugal', 'Lisbon', 55, 48, 2200),
  ('Spain', 'Barcelona', 60, 52, 2400),
  ('Thailand', 'Bangkok', 38, 25, 1500),
  ('Thailand', 'Chiang Mai', 32, 20, 1200),
  ('Vietnam', 'Ho Chi Minh City', 30, 18, 1100),
  ('Indonesia', 'Bali', 35, 22, 1300),
  ('Mexico', 'Mexico City', 42, 28, 1600),
  ('Colombia', 'Medellin', 35, 22, 1300),
  ('South Korea', 'Seoul', 80, 72, 3000),
  ('Japan', 'Tokyo', 82, 68, 3200),
  ('Singapore', 'Singapore', 95, 110, 4000),
  ('Australia', 'Sydney', 90, 88, 3800),
  ('Canada', 'Toronto', 82, 78, 3400),
  ('Poland', 'Warsaw', 48, 38, 1900),
  ('Georgia', 'Tbilisi', 38, 25, 1400),
  ('Estonia', 'Tallinn', 55, 50, 2200);

-- 기업 데이터
INSERT OR IGNORE INTO companies (name, logo_url, website, size, industry, description, headquarters_country, headquarters_city, timezone, remote_policy, rating, review_count, founded_year) VALUES
  ('GitLab', NULL, 'https://gitlab.com', '501+', 'Software Development', '100% 원격 근무를 선도하는 DevOps 플랫폼 회사. 전 세계 65개국에 직원 보유.', 'United States', 'San Francisco (Remote-First)', 'UTC-8', 'fully_remote', 4.8, 1842, 2011),
  ('Automattic', NULL, 'https://automattic.com', '1001+', 'Technology', 'WordPress.com, WooCommerce 등을 운영하는 완전 원격 회사. 직원 100% 원격 근무.', 'United States', 'San Francisco (Remote)', 'UTC-8', 'fully_remote', 4.7, 923, 2005),
  ('Basecamp', NULL, 'https://basecamp.com', '51-200', 'Software Development', '원격 근무 문화의 선구자. "Remote" 저자 Jason Fried의 회사.', 'United States', 'Chicago', 'UTC-6', 'fully_remote', 4.6, 456, 1999),
  ('Doist', NULL, 'https://doist.com', '51-200', 'Productivity Software', 'Todoist, Twist를 만드는 비동기 원격 팀. 전 세계 35개국 팀원.', 'Portugal', 'Lisbon (Remote)', 'UTC+0', 'fully_remote', 4.9, 312, 2007),
  ('Hotjar', NULL, 'https://hotjar.com', '201-500', 'Analytics', '사용자 행동 분석 툴을 만드는 Malta 기반의 완전 원격 회사.', 'Malta', 'St Julian''s', 'UTC+1', 'fully_remote', 4.5, 678, 2014),
  ('Remote', NULL, 'https://remote.com', '501+', 'HR Technology', '글로벌 인력 관리 플랫폼. 100개국 이상에서 채용 가능한 EOR 서비스.', 'United States', 'San Francisco', 'UTC-8', 'fully_remote', 4.6, 534, 2019),
  ('Deel', NULL, 'https://deel.com', '1001+', 'Fintech / HR', '글로벌 급여 및 인력 관리 플랫폼. 150개국 계약 지원.', 'United States', 'San Francisco', 'UTC-8', 'fully_remote', 4.4, 891, 2019),
  ('Toptal', NULL, 'https://toptal.com', '201-500', 'Talent Marketplace', '상위 3% 프리랜서 네트워크. 완전 원격 운영.', 'United States', 'Wilmington', 'UTC-5', 'fully_remote', 4.3, 1205, 2010),
  ('Stripe', NULL, 'https://stripe.com', '5000+', 'Fintech', '글로벌 결제 인프라 회사. 원격 친화적 문화.', 'United States', 'San Francisco', 'UTC-8', 'remote_first', 4.7, 3421, 2010),
  ('Shopify', NULL, 'https://shopify.com', '10000+', 'E-commerce', '이커머스 플랫폼 선두 주자. "Digital by default" 정책.', 'Canada', 'Ottawa', 'UTC-5', 'remote_first', 4.5, 5678, 2006),
  ('Buffer', NULL, 'https://buffer.com', '51-200', 'Social Media Tools', '소셜 미디어 관리 툴. 완전 투명한 급여 공개 원격 회사.', 'United States', 'San Francisco (Remote)', 'UTC-8', 'fully_remote', 4.8, 289, 2010),
  ('ConvertKit', NULL, 'https://convertkit.com', '51-200', 'Email Marketing', '크리에이터를 위한 이메일 마케팅 플랫폼. 완전 원격.', 'United States', 'Boise (Remote)', 'UTC-7', 'fully_remote', 4.6, 178, 2013),
  ('Zapier', NULL, 'https://zapier.com', '501+', 'Automation', '앱 자동화 플랫폼. 설립 초기부터 완전 원격 운영.', 'United States', 'Sunnyvale (Remote)', 'UTC-8', 'fully_remote', 4.7, 1023, 2011),
  ('HubSpot', NULL, 'https://hubspot.com', '5000+', 'CRM / Marketing', 'CRM 및 마케팅 자동화 플랫폼. 유연한 원격 정책.', 'United States', 'Cambridge, MA', 'UTC-5', 'remote_first', 4.4, 7892, 2006),
  ('Figma', NULL, 'https://figma.com', '1001+', 'Design Tools', '콜라보레이션 디자인 툴. 원격 팀을 위한 도구를 만드는 원격 친화 회사.', 'United States', 'San Francisco', 'UTC-8', 'remote_first', 4.6, 2341, 2012);

-- 공고 데이터
INSERT OR IGNORE INTO jobs (company_id, title, slug, category, subcategory, description, requirements, nice_to_have, remote_type, contract_type, duration, experience_level, salary_min, salary_max, salary_currency, salary_period, required_timezone, timezone_overlap_hours, preferred_timezones, async_work_percentage, monthly_meeting_count, equipment_provided, coworking_budget, tools, skills_required, skills_preferred, languages_required, is_featured) VALUES
(1, 'Senior Frontend Engineer (React)', 'senior-frontend-engineer-react-gitlab', 'Engineering', 'Frontend', 
'GitLab에서 수백만 개발자가 사용하는 웹 인터페이스를 개발할 Senior Frontend Engineer를 찾습니다. 완전 원격 환경에서 비동기적으로 협업하며 오픈소스 기여도 환영합니다. 당신의 코드가 전 세계 DevOps 워크플로우에 직접적인 영향을 미칩니다.',
'["React/Vue.js 5년 이상", "TypeScript 필수", "GraphQL API 연동 경험", "성능 최적화 경험", "영어 비즈니스 레벨"]',
'["GitLab 오픈소스 기여 경험", "Ruby on Rails 이해", "접근성(WCAG) 구현 경험"]',
'fully_remote', 'full_time', 'permanent', 'senior',
120000, 180000, 'USD', 'yearly',
NULL, 0, '["UTC-8","UTC-5","UTC+0","UTC+1","UTC+2"]',
80, 4, 1, 250,
'["GitLab","Slack","Zoom","Figma","Linear"]',
'["React","TypeScript","GraphQL","Jest","Webpack"]',
'["Vue.js","Ruby","PostgreSQL","Docker"]',
'["English"]', 1),

(2, 'Full Stack Engineer (WordPress/PHP)', 'fullstack-engineer-wordpress-automattic', 'Engineering', 'Full Stack',
'WordPress.com을 수억 명의 사용자가 더 잘 사용할 수 있도록 돕는 Full Stack Engineer를 모집합니다. 100% 비동기 원격 문화에서 전 세계 팀원들과 협업합니다.',
'["PHP 4년 이상", "JavaScript/React 3년 이상", "MySQL 경험", "WordPress 개발 경험", "영어 유창"]',
'["Gutenberg 블록 에디터 경험", "WooCommerce 플러그인 개발", "A/B 테스팅 경험"]',
'fully_remote', 'full_time', 'permanent', 'mid',
90000, 140000, 'USD', 'yearly',
NULL, 0, NULL,
90, 2, 1, 200,
'["Slack","Zoom","Notion","GitHub","P2"]',
'["PHP","JavaScript","React","MySQL","WordPress"]',
'["TypeScript","GraphQL","Redis","Docker"]',
'["English"]', 0),

(4, 'Product Designer (Mobile & Web)', 'product-designer-doist', 'Design', 'Product Design',
'수백만 명이 사용하는 Todoist의 모바일/웹 경험을 디자인합니다. 완전 비동기 팀에서 사용자 중심 디자인 프로세스를 이끌 디자이너를 찾습니다.',
'["Figma 전문가 수준", "모바일 UI/UX 디자인 4년 이상", "사용자 리서치 경험", "디자인 시스템 구축 경험", "영어 고급"]',
'["iOS/Android 네이티브 디자인 가이드라인 이해", "프로토타이핑 경험", "개발자와의 협업 경험"]',
'fully_remote', 'full_time', 'permanent', 'mid',
80000, 120000, 'USD', 'yearly',
'UTC+0', 4, '["UTC-5","UTC+0","UTC+1","UTC+2","UTC+3"]',
75, 6, 1, 300,
'["Figma","Notion","Twist","Loom","Maze"]',
'["Figma","User Research","Design Systems","Prototyping","Mobile Design"]',
'["Framer","Principle","Zeplin","After Effects"]',
'["English"]', 1),

(3, 'Backend Engineer (Ruby on Rails)', 'backend-engineer-ruby-basecamp', 'Engineering', 'Backend',
'Hey.com과 Basecamp 앱의 백엔드를 담당할 엔지니어를 찾습니다. 작은 팀에서 큰 임팩트를 만들고 싶은 분을 환영합니다.',
'["Ruby on Rails 4년 이상", "PostgreSQL 심화", "RESTful API 설계", "TDD/BDD 경험", "영어 비즈니스 레벨"]',
'["Redis/Memcached 캐싱", "배포 자동화(CI/CD)", "성능 튜닝 경험"]',
'fully_remote', 'full_time', 'permanent', 'senior',
130000, 170000, 'USD', 'yearly',
'UTC-6', 6, '["UTC-8","UTC-7","UTC-6","UTC-5"]',
70, 5, 1, 150,
'["Basecamp","Hey","GitHub","Slack"]',
'["Ruby","Rails","PostgreSQL","Redis","Linux"]',
'["Docker","Kubernetes","AWS","Elasticsearch"]',
'["English"]', 0),

(5, 'Growth Marketing Manager', 'growth-marketing-manager-hotjar', 'Marketing', 'Growth',
'Hotjar의 Product-Led Growth 전략을 실행할 마케터를 찾습니다. 데이터 기반으로 사용자 획득 및 활성화 퍼널을 최적화합니다.',
'["PLG 또는 B2B SaaS 마케팅 3년 이상", "Google Analytics, Mixpanel 활용 능력", "A/B 테스팅 경험", "SEO/SEM 실무 경험", "영어 유창"]',
'["Hotjar/FullStory 사용 경험", "이메일 자동화 경험", "SQL 기본 이해"]',
'fully_remote', 'full_time', 'permanent', 'mid',
70000, 100000, 'USD', 'yearly',
'UTC+1', 4, '["UTC-5","UTC+0","UTC+1","UTC+2","UTC+3"]',
65, 8, 1, 200,
'["Hotjar","HubSpot","Slack","Notion","Figma"]',
'["Growth Marketing","SEO","SEM","Analytics","A/B Testing","Email Marketing"]',
'["SQL","Python","Zapier","Webflow"]',
'["English"]', 0),

(6, 'Senior Software Engineer (Payments)', 'senior-software-engineer-payments-remote', 'Engineering', 'Backend',
'전 세계 기업들이 글로벌 인력에게 급여를 지급할 수 있는 결제 인프라를 구축합니다. 복잡한 국제 결제 시스템 문제를 해결하는 엔지니어를 찾습니다.',
'["Node.js 또는 Python 5년 이상", "결제 시스템 구축 경험", "Stripe/PayPal API 연동", "보안 및 규정 준수 이해", "영어 비즈니스 레벨"]',
'["국제 송금 서비스 경험", "블록체인/암호화폐 이해", "SOC2 준수 경험"]',
'fully_remote', 'full_time', 'permanent', 'senior',
140000, 200000, 'USD', 'yearly',
NULL, 0, NULL,
80, 6, 1, 300,
'["Slack","Linear","GitHub","Notion"]',
'["Node.js","PostgreSQL","Redis","Stripe","Kubernetes","AWS"]',
'["Python","Go","Blockchain","Kafka"]',
'["English"]', 1),

(13, 'DevOps Engineer (Remote)', 'devops-engineer-zapier', 'Engineering', 'DevOps',
'Zapier의 인프라를 관리하고 개발팀이 빠르게 배포할 수 있도록 지원하는 DevOps 엔지니어를 찾습니다.',
'["AWS/GCP 3년 이상", "Kubernetes 운영 경험", "CI/CD 파이프라인 구축", "Infrastructure as Code (Terraform)", "영어 비즈니스 레벨"]',
'["Datadog 또는 유사 모니터링 도구", "Python/Go 스크립팅", "보안 감사 경험"]',
'fully_remote', 'full_time', 'permanent', 'mid',
100000, 150000, 'USD', 'yearly',
NULL, 0, NULL,
75, 6, 1, 200,
'["Slack","GitHub","Datadog","PagerDuty","Terraform"]',
'["AWS","Kubernetes","Terraform","Docker","CI/CD","Python"]',
'["Go","Ansible","Prometheus","Grafana"]',
'["English"]', 0),

(11, 'Content Marketing Strategist', 'content-marketing-strategist-buffer', 'Marketing', 'Content',
'Buffer의 블로그, SNS, 미디어 콘텐츠 전략을 이끌 콘텐츠 마케터를 찾습니다. 원격 근무 문화와 스타트업 마케팅에 대한 글쓰기 경험자 우대.',
'["콘텐츠 마케팅 3년 이상", "SEO 최적화 경험", "영어 원어민 수준 글쓰기", "소셜 미디어 전략 경험", "데이터 분석 능력"]',
'["비디오/팟캐스트 콘텐츠 경험", "마케팅 자동화 도구 경험", "원격 근무/노마드 관련 콘텐츠 경험"]',
'fully_remote', 'full_time', 'permanent', 'mid',
65000, 95000, 'USD', 'yearly',
NULL, 0, '["UTC-8","UTC-5","UTC+0","UTC+1"]',
80, 4, 1, 150,
'["Buffer","Slack","Notion","Loom","Zoom"]',
'["Content Strategy","SEO","Social Media","Copywriting","Analytics"]',
'["HubSpot","Webflow","Ahrefs","WordPress"]',
'["English"]', 0),

(9, 'Senior iOS Engineer', 'senior-ios-engineer-stripe', 'Engineering', 'Mobile',
'Stripe의 모바일 결제 SDK와 앱을 개발하는 iOS 엔지니어를 찾습니다. 수백만 개발자가 의존하는 SDK를 만드는 팀에 합류하세요.',
'["Swift 5년 이상", "iOS SDK 개발 경험", "Core Data, URLSession 등 네이티브 API", "Unit/UI 테스팅", "영어 유창"]',
'["결제 또는 금융 앱 경험", "오픈소스 라이브러리 기여 경험", "SwiftUI 경험"]',
'remote_first', 'full_time', 'permanent', 'senior',
150000, 220000, 'USD', 'yearly',
'UTC-8', 6, '["UTC-8","UTC-5","UTC+0","UTC+1"]',
60, 8, 1, 400,
'["Slack","GitHub","Figma","Linear","Zoom"]',
'["Swift","iOS","Xcode","Core Data","REST APIs","Git"]',
'["SwiftUI","Objective-C","React Native","Android"]',
'["English"]', 0),

(10, 'UX Researcher (Remote)', 'ux-researcher-shopify', 'Design', 'Research',
'Shopify 판매자 경험을 개선하기 위한 사용자 리서치를 이끌 UX Researcher를 찾습니다. 이커머스 도메인에 대한 깊은 이해를 가진 분을 환영합니다.',
'["UX 리서치 4년 이상", "정성/정량 리서치 방법론", "사용성 테스트 진행 경험", "UserTesting, Lookback 활용", "영어 유창"]',
'["이커머스 도메인 경험", "Figma 프로토타입 이해", "통계 분석 기본 이해"]',
'remote_first', 'full_time', 'permanent', 'mid',
85000, 125000, 'USD', 'yearly',
'UTC-5', 4, '["UTC-8","UTC-7","UTC-6","UTC-5"]',
65, 6, 1, 200,
'["Figma","Notion","Zoom","UserTesting","Dovetail"]',
'["UX Research","Usability Testing","Surveys","Data Analysis","Figma"]',
'["Qualtrics","Tableau","Python","SQL"]',
'["English"]', 0),

(7, 'Frontend Engineer (React/Next.js)', 'frontend-engineer-deel', 'Engineering', 'Frontend',
'Deel의 HR 플랫폼 프론트엔드를 개발합니다. 150개국의 사용자가 매일 사용하는 복잡한 인터페이스를 구축하는 팀에 합류하세요.',
'["React/Next.js 3년 이상", "TypeScript 필수", "REST API 연동 경험", "반응형 디자인", "영어 비즈니스 레벨"]',
'["국제화(i18n) 구현 경험", "성능 최적화 경험", "Storybook 사용 경험"]',
'fully_remote', 'full_time', 'permanent', 'mid',
80000, 130000, 'USD', 'yearly',
NULL, 0, NULL,
70, 8, 1, 200,
'["Slack","GitHub","Figma","Linear","Notion"]',
'["React","Next.js","TypeScript","CSS","REST APIs"]',
'["GraphQL","Docker","i18n","Testing Library"]',
'["English"]', 0),

(12, 'Email Marketing Specialist', 'email-marketing-specialist-convertkit', 'Marketing', 'Email',
'ConvertKit에서 크리에이터들이 더 효과적으로 이메일 마케팅을 할 수 있도록 플랫폼 마케팅을 담당합니다.',
'["이메일 마케팅 2년 이상", "이메일 자동화 설계 경험", "카피라이팅 능력", "A/B 테스팅 경험", "영어 유창"]',
'["ConvertKit 사용 경험", "크리에이터 이코노미 이해", "HTML/CSS 기본 이해"]',
'fully_remote', 'full_time', 'permanent', 'junior',
55000, 80000, 'USD', 'yearly',
NULL, 0, '["UTC-8","UTC-7","UTC-6","UTC-5"]',
80, 5, 1, 100,
'["ConvertKit","Slack","Notion","Loom"]',
'["Email Marketing","Copywriting","A/B Testing","Analytics","Segmentation"]',
'["SQL","HTML","CSS","Figma"]',
'["English"]', 0),

(8, 'Senior Full Stack Developer (Contract)', 'senior-fullstack-developer-contract-toptal', 'Engineering', 'Full Stack',
'Toptal 최상위 클라이언트를 위한 6개월 컨트랙 포지션. 핀테크 스타트업의 핵심 기능 개발을 리드합니다. 시간당 $120-150 + 스톡옵션.',
'["풀스택 개발 7년 이상", "React + Node.js 전문", "PostgreSQL/MongoDB 심화", "마이크로서비스 아키텍처", "영어 유창"]',
'["AWS 아키텍처 경험", "결제 시스템 통합", "팀 리드 경험"]',
'fully_remote', 'contract', 'mid_term', 'senior',
100, 150, 'USD', 'hourly',
'UTC-5', 4, '["UTC-8","UTC-5","UTC+0","UTC+1"]',
60, 10, 0, 0,
'["GitHub","Slack","Zoom","Jira","Confluence"]',
'["React","Node.js","PostgreSQL","AWS","Docker","TypeScript"]',
'["Kubernetes","GraphQL","Redis","Stripe"]',
'["English"]', 1),

(15, 'Product Manager - Collaboration', 'product-manager-collaboration-figma', 'Product', 'Product Management',
'Figma의 실시간 협업 기능을 개선하는 PM을 찾습니다. 디자인 툴의 미래를 함께 만들어갑시다.',
'["B2B SaaS PM 경험 4년 이상", "데이터 기반 의사결정 경험", "엔지니어/디자이너와의 협업 경험", "사용자 리서치 경험", "영어 유창"]',
'["디자인 도구 또는 협업 툴 PM 경험", "SQL 기본 이해", "Figma 파워 유저"]',
'remote_first', 'full_time', 'permanent', 'senior',
130000, 190000, 'USD', 'yearly',
'UTC-8', 6, '["UTC-8","UTC-5","UTC+0","UTC+1"]',
60, 10, 1, 400,
'["Figma","Slack","Notion","Linear","Amplitude"]',
'["Product Management","Roadmapping","User Research","Data Analysis","Agile"]',
'["SQL","Figma","A/B Testing","Mixpanel","Jira"]',
'["English"]', 0),

(14, 'Customer Success Manager (APAC)', 'customer-success-manager-apac-hubspot', 'Operations', 'Customer Success',
'HubSpot APAC 지역 주요 고객의 성공을 책임질 CSM. 한국어/일본어 가능자 우대.',
'["B2B SaaS CSM 경험 3년 이상", "고객 포트폴리오 관리 경험", "CRM 도구 활용 능력", "한국어 또는 일본어 비즈니스 레벨", "영어 유창"]',
'["HubSpot CRM 사용 경험", "마케팅 자동화 이해", "데이터 분석 능력"]',
'remote_first', 'full_time', 'permanent', 'mid',
70000, 110000, 'USD', 'yearly',
'UTC+9', 6, '["UTC+7","UTC+8","UTC+9","UTC+10"]',
50, 15, 1, 200,
'["HubSpot","Slack","Zoom","Gainsight","Notion"]',
'["Customer Success","Account Management","CRM","Communication","Problem Solving"]',
'["HubSpot","Salesforce","SQL","Korean","Japanese"]',
'["English","Korean"]', 0);
PRAGMA foreign_keys=ON;
